### ISSUE TITLE
Multiple MODS datastreams generated on ingest

### ISSUE THREAD

**Issue by lucasvanschaik** [discoverygarden/islandora_handle#36]
In some cases when adding the handle to the MODS (and/or the DC) datastream during the derivative generation of an ingest, multiple (sometimes thousands) of MODS datastream versions are generated, all containing the handle and all are exactly the same.
We experienced this in our production system, but then it went away. Now I have it on my development system. I can reproduce it there, but when I install a fresh Virtual Machine, it does not appear to be infected.

This is what I do and what happens:
- enable islandora_handle last version (in debug mode)
- setup for content model basic image (create MODS using handle_the_MODS.xsl)
- ingest a PNG image in the basic image collection using the web interface
- the ingest seems stuck.. it takes a long time...
- when I abort the ingest, the TN is not generated but the MODS has a handle
- there are a few hundred versions of the MODS and DC datastream
![image](https://user-images.githubusercontent.com/12761910/68278873-8bcd9800-0072-11ea-9b2a-834104c6c42f.png)
- they are all the same and contain a handle, except for the first
![image](https://user-images.githubusercontent.com/12761910/68278955-bae40980-0072-11ea-9e6e-1f39ce4ed148.png)
....
![image](https://user-images.githubusercontent.com/12761910/68279019-d818d800-0072-11ea-829a-eddfa056549f.png)
- and apparently the generation of the MODS  continues in the background...
![image](https://user-images.githubusercontent.com/12761910/68279072-f8e12d80-0072-11ea-8b0a-4162e52b0920.png)

After debugging the problem and reviewing the code, the only reason I can come up with of why this is happening, is that in the function appendHandleToMetadata the old version of the datastream is used (https://github.com/discoverygarden/islandora_handle/blob/b6faa69f956457180cf91cf2f3b455bcb2e17450/includes/IslandoraHandleHandleHandler.class.inc#L135) every time, and therefore the equals check (https://github.com/discoverygarden/islandora_handle/blob/b6faa69f956457180cf91cf2f3b455bcb2e17450/includes/IslandoraHandleHandleHandler.class.inc#L146) always returns false.

One way of solving this issue is to only actually change the datastreams when there is a new handle at all.
In islandora_handle_append_handle_from_configuration 
(https://github.com/discoverygarden/islandora_handle/blob/b6faa69f956457180cf91cf2f3b455bcb2e17450/includes/derivatives.inc#L21) the check for the handle is done via readHandle (https://github.com/discoverygarden/islandora_handle/blob/b6faa69f956457180cf91cf2f3b455bcb2e17450/includes/derivatives.inc#L29), but that if-statement is closed before updating the metadata. If the updating of the metadata is included in the if-statement, then this issue is solved. 
See https://github.com/LeidenUniversityLibrary/islandora_handle/commit/b6dbc66eccf85d0d7ac93fedac0f2b58fa07d017 for possible solution.

**Comment by qadan** [comment]
Hi @lucasvanschaik, thanks for this! Looking over the proposed solution, the code seems sound. I'm going to run a couple tests here, but I think it seems largely fine for a PR/merge - the only issue with it being that some of the code comments are over the 80-character limit required by Drupal's coding standards. Other than that, I'll just make sure it passes a smoke test locally and then I think everything is perfect

**Comment by lucasvanschaik** [comment]
This issue can also be closed because it is resolved in the PR and merged.
